### ISSUE TITLE
Add fatigue, engineer, etc. settings to agm log

### ISSUE THREAD

**Issue by Cephel** [a3g/a3g-framework-modules#10]

**Comment by BaerMitUmlaut** [comment]
https://github.com/KoffeinFlummi/AGM/blob/master/AGM_Movement/clientInit.sqf

**Comment by Cephel** [comment]
Wat

**Comment by BaerMitUmlaut** [comment]
Apart from showing weight the whole module doesn't do anything. There is no point in logging fatigue settings.

**Comment by Cephel** [comment]
Ah, righto

**Comment by Cephel** [comment]
Fixed in f0588f97c588f35d2a5ed19339704bb360cd4dfd
