### ISSUE TITLE
Anti vehicle steal: UAV's cannot be remote controlled directly

### ISSUE THREAD

**Issue by Cephel** [a3g/a3g-framework-modules#14]
when the Anti-Vehicle steal module executes it locks UAVs from the players. probable that the UAV autonomy is considered a "crew member" for engine reasons not sure of the best way to resolve this issue

**Comment by Cephel** [comment]
Just to clarify, we're talking about the UGV, right? The ground based autonomous car? If so yes, that is indeed the reason. The "driver" is considered an AI and thus it locks the vehicle. I'll think of something

**Comment by Ciaran-A3G** [comment]
we're talking all Autonomous vehicles including Darters

**Comment by Cephel** [comment]
Possible solutions:
- Whitelist all UAV classnames
- whitelist ála `unit setVariable[...]`
